name: Deploy MkDocs to GitHub Pages

on:
  push:
    branches:
      - main  # Trigger this workflow on pushes to the `main` branch
  pull_request:
    branches:
      - main  # Optional: Run checks on pull requests to `main`

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # Step 2: Set up Python environment
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    # Step 3: Install dependencies
    - name: Install MkDocs and dependencies
      run: |
        pip install mkdocs mkdocs-material
        pip install mkdocs-material-extensions  # Optional extensions/plugins

    # Step 4: Build the documentation
    - name: Build MkDocs site
      run: mkdocs build

    # Step 5: Deploy to GitHub Pages
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./site
